CREATE TABLE alert (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_user_id BIGINT NOT NULL REFERENCES app_user(id),
    owned_item_id BIGINT NOT NULL REFERENCES owned_item(id),
    price_snapshot_id BIGINT NOT NULL REFERENCES price_snapshot(id),
    item_display_name VARCHAR(500) NOT NULL,
    purchase_price_sgd NUMERIC(19, 2) NOT NULL,
    current_market_value_sgd NUMERIC(19, 2) NOT NULL,
    gain_amount_sgd NUMERIC(19, 2) NOT NULL,
    gain_percentage NUMERIC(19, 4) NOT NULL,
    confidence_rating VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    triggered_at TIMESTAMP WITH TIME ZONE NOT NULL,
    dismissed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_alert_gain_nonnegative CHECK (gain_amount_sgd >= 0),
    CONSTRAINT uq_alert_owned_item_price_snapshot UNIQUE (owned_item_id, price_snapshot_id)
);

CREATE INDEX idx_alert_user_status_triggered ON alert (app_user_id, status, triggered_at DESC);
