ALTER TABLE owned_item
ADD COLUMN item_status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE';

UPDATE owned_item
SET item_status = CASE
    WHEN archived_at IS NULL THEN 'ACTIVE'
    ELSE 'DELETED'
END;

CREATE TABLE owned_item_disposal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_user_id BIGINT NOT NULL REFERENCES app_user(id),
    owned_item_id BIGINT NOT NULL REFERENCES owned_item(id),
    disposal_type VARCHAR(50) NOT NULL,
    disposal_date DATE NOT NULL,
    proceeds_value_sgd NUMERIC(19, 2),
    fees_sgd NUMERIC(19, 2) NOT NULL DEFAULT 0,
    net_proceeds_sgd NUMERIC(19, 2) NOT NULL DEFAULT 0,
    original_purchase_price_sgd NUMERIC(19, 2) NOT NULL,
    realized_gain_loss_sgd NUMERIC(19, 2) NOT NULL DEFAULT 0,
    realized_gain_loss_percent NUMERIC(19, 4) NOT NULL DEFAULT 0,
    notes VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_owned_item_disposal_owned_item UNIQUE (owned_item_id),
    CONSTRAINT chk_disposal_fees_nonnegative CHECK (fees_sgd >= 0),
    CONSTRAINT chk_disposal_original_purchase_nonnegative CHECK (original_purchase_price_sgd >= 0)
);

CREATE INDEX idx_owned_item_status_owner ON owned_item(app_user_id, item_status, created_at DESC);
CREATE INDEX idx_owned_item_disposal_owner_date ON owned_item_disposal(app_user_id, disposal_date DESC, id DESC);
