CREATE TABLE trade_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_user_id BIGINT NOT NULL REFERENCES app_user(id),
    name VARCHAR(255) NOT NULL,
    mode VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    total_outgoing_market_value_sgd NUMERIC(19, 2) NOT NULL DEFAULT 0,
    total_incoming_market_value_sgd NUMERIC(19, 2) NOT NULL DEFAULT 0,
    total_outgoing_agreed_value_sgd NUMERIC(19, 2) NOT NULL DEFAULT 0,
    total_incoming_agreed_value_sgd NUMERIC(19, 2) NOT NULL DEFAULT 0,
    total_outgoing_adjusted_value_sgd NUMERIC(19, 2) NOT NULL DEFAULT 0,
    total_incoming_adjusted_value_sgd NUMERIC(19, 2) NOT NULL DEFAULT 0,
    net_difference_sgd NUMERIC(19, 2) NOT NULL DEFAULT 0,
    trade_imbalance_sgd NUMERIC(19, 2) NOT NULL DEFAULT 0,
    fairness_result VARCHAR(50) NOT NULL,
    confidence_rating VARCHAR(50) NOT NULL,
    notes VARCHAR(1000),
    analysed_at TIMESTAMP WITH TIME ZONE,
    executed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_trade_totals_nonnegative CHECK (
        total_outgoing_market_value_sgd >= 0
        AND total_incoming_market_value_sgd >= 0
        AND total_outgoing_agreed_value_sgd >= 0
        AND total_incoming_agreed_value_sgd >= 0
        AND total_outgoing_adjusted_value_sgd >= 0
        AND total_incoming_adjusted_value_sgd >= 0
    )
);

CREATE TABLE trade_transaction_side (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_transaction_id BIGINT NOT NULL REFERENCES trade_transaction(id),
    side_type VARCHAR(50) NOT NULL,
    trade_percentage NUMERIC(9, 4) NOT NULL DEFAULT 100,
    total_market_value_sgd NUMERIC(19, 2) NOT NULL DEFAULT 0,
    total_agreed_value_sgd NUMERIC(19, 2) NOT NULL DEFAULT 0,
    total_adjusted_value_sgd NUMERIC(19, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_trade_side_type UNIQUE (trade_transaction_id, side_type),
    CONSTRAINT chk_trade_percentage_positive CHECK (trade_percentage > 0),
    CONSTRAINT chk_trade_side_totals_nonnegative CHECK (
        total_market_value_sgd >= 0
        AND total_agreed_value_sgd >= 0
        AND total_adjusted_value_sgd >= 0
    )
);

CREATE TABLE trade_transaction_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_transaction_id BIGINT NOT NULL REFERENCES trade_transaction(id),
    trade_transaction_side_id BIGINT NOT NULL REFERENCES trade_transaction_side(id),
    side_type VARCHAR(50) NOT NULL,
    outgoing_owned_item_id BIGINT REFERENCES owned_item(id),
    card_id BIGINT REFERENCES card(id),
    incoming_owned_item_id BIGINT REFERENCES owned_item(id),
    disposal_id BIGINT REFERENCES owned_item_disposal(id),
    incoming_variant VARCHAR(50),
    incoming_condition VARCHAR(50),
    agreed_value_sgd NUMERIC(19, 2) NOT NULL DEFAULT 0,
    market_value_sgd NUMERIC(19, 2) NOT NULL DEFAULT 0,
    adjusted_value_sgd NUMERIC(19, 2) NOT NULL DEFAULT 0,
    allocated_cost_basis_sgd NUMERIC(19, 2),
    confidence_rating VARCHAR(50) NOT NULL,
    notes VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_trade_item_values_nonnegative CHECK (
        agreed_value_sgd >= 0
        AND market_value_sgd >= 0
        AND adjusted_value_sgd >= 0
        AND (allocated_cost_basis_sgd IS NULL OR allocated_cost_basis_sgd >= 0)
    )
);

ALTER TABLE owned_item_disposal
ADD COLUMN trade_transaction_id BIGINT REFERENCES trade_transaction(id);

CREATE INDEX idx_trade_transaction_owner_created ON trade_transaction(app_user_id, created_at DESC);
CREATE INDEX idx_trade_side_transaction ON trade_transaction_side(trade_transaction_id);
CREATE INDEX idx_trade_item_transaction ON trade_transaction_item(trade_transaction_id);
CREATE INDEX idx_trade_item_side ON trade_transaction_item(trade_transaction_side_id);
CREATE INDEX idx_trade_item_outgoing_owned_item ON trade_transaction_item(outgoing_owned_item_id);
CREATE INDEX idx_trade_item_incoming_owned_item ON trade_transaction_item(incoming_owned_item_id);
CREATE INDEX idx_disposal_trade_transaction ON owned_item_disposal(trade_transaction_id);
