CREATE TABLE sealed_product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    product_type VARCHAR(80) NOT NULL,
    language_market VARCHAR(50) NOT NULL,
    set_name VARCHAR(255),
    release_date DATE,
    image_url VARCHAR(1000),
    catalog_source VARCHAR(80) NOT NULL DEFAULT 'MANUAL',
    verification_status VARCHAR(80) NOT NULL DEFAULT 'UNVERIFIED',
    notes VARCHAR(1000),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_sealed_product_type CHECK (
        product_type IN ('BOOSTER_BOX', 'BOOSTER_PACK', 'ETB', 'COLLECTION_BOX', 'PROMO_BOX', 'OTHER')
    ),
    CONSTRAINT chk_sealed_product_language CHECK (
        language_market IN ('ENGLISH', 'JAPANESE', 'CHINESE', 'OTHER')
    ),
    CONSTRAINT chk_sealed_product_catalog_source CHECK (catalog_source IN ('MANUAL', 'POKEMON_TCG_API')),
    CONSTRAINT chk_sealed_product_verification CHECK (verification_status IN ('UNVERIFIED', 'VERIFIED'))
);

ALTER TABLE owned_item
ADD COLUMN asset_type VARCHAR(50) NOT NULL DEFAULT 'CARD';

ALTER TABLE owned_item
ADD COLUMN sealed_product_id BIGINT REFERENCES sealed_product(id);

ALTER TABLE owned_item
ADD COLUMN sealed_condition VARCHAR(80);

ALTER TABLE owned_item
ALTER COLUMN card_id DROP NOT NULL;

ALTER TABLE owned_item
ALTER COLUMN item_condition DROP NOT NULL;

ALTER TABLE owned_item
ADD CONSTRAINT chk_owned_item_asset_reference CHECK (
    (asset_type = 'CARD' AND card_id IS NOT NULL AND sealed_product_id IS NULL AND item_condition IS NOT NULL)
    OR
    (asset_type = 'SEALED_PRODUCT' AND card_id IS NULL AND sealed_product_id IS NOT NULL AND sealed_condition IS NOT NULL)
);

ALTER TABLE price_snapshot
ADD COLUMN asset_type VARCHAR(50) NOT NULL DEFAULT 'CARD';

ALTER TABLE price_snapshot
ADD COLUMN sealed_product_id BIGINT REFERENCES sealed_product(id);

ALTER TABLE price_snapshot
ALTER COLUMN card_id DROP NOT NULL;

ALTER TABLE price_snapshot
ADD CONSTRAINT chk_price_snapshot_asset_reference CHECK (
    (asset_type = 'CARD' AND card_id IS NOT NULL AND sealed_product_id IS NULL)
    OR
    (asset_type = 'SEALED_PRODUCT' AND card_id IS NULL AND sealed_product_id IS NOT NULL)
);

ALTER TABLE trade_transaction_item
ADD COLUMN asset_type VARCHAR(50) NOT NULL DEFAULT 'CARD';

ALTER TABLE trade_transaction_item
ADD COLUMN sealed_product_id BIGINT REFERENCES sealed_product(id);

CREATE INDEX idx_sealed_product_active_name ON sealed_product(active, name);
CREATE INDEX idx_owned_item_sealed_product ON owned_item(sealed_product_id);
CREATE INDEX idx_price_snapshot_sealed_product_time
    ON price_snapshot(sealed_product_id, calculated_at DESC, id DESC);
CREATE INDEX idx_trade_item_sealed_product ON trade_transaction_item(sealed_product_id);
