CREATE TABLE grading_fee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grading_company VARCHAR(50) NOT NULL DEFAULT 'PSA',
    service_level_name VARCHAR(255) NOT NULL,
    fee_sgd NUMERIC(19, 2) NOT NULL,
    estimated_turnaround_days INTEGER NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_grading_fee_company CHECK (grading_company IN ('PSA')),
    CONSTRAINT chk_grading_fee_nonnegative CHECK (fee_sgd >= 0),
    CONSTRAINT chk_grading_fee_turnaround_positive CHECK (estimated_turnaround_days > 0)
);

CREATE TABLE grading_analysis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_user_id BIGINT NOT NULL REFERENCES app_user(id),
    owned_item_id BIGINT NOT NULL REFERENCES owned_item(id),
    grading_fee_id BIGINT REFERENCES grading_fee(id),
    raw_value_sgd NUMERIC(19, 2) NOT NULL,
    psa8_value_sgd NUMERIC(19, 2) NOT NULL,
    psa9_value_sgd NUMERIC(19, 2) NOT NULL,
    psa10_value_sgd NUMERIC(19, 2) NOT NULL,
    grading_fee_sgd NUMERIC(19, 2) NOT NULL,
    estimated_turnaround_days INTEGER NOT NULL,
    opportunity_cost_sgd NUMERIC(19, 2) NOT NULL DEFAULT 0,
    minimum_profit_threshold_sgd NUMERIC(19, 2) NOT NULL DEFAULT 50,
    recommendation VARCHAR(80) NOT NULL,
    confidence_rating VARCHAR(50) NOT NULL,
    notes VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_grading_analysis_values_nonnegative CHECK (
        raw_value_sgd >= 0
        AND psa8_value_sgd >= 0
        AND psa9_value_sgd >= 0
        AND psa10_value_sgd >= 0
        AND grading_fee_sgd >= 0
        AND opportunity_cost_sgd >= 0
        AND minimum_profit_threshold_sgd >= 0
    ),
    CONSTRAINT chk_grading_analysis_turnaround_positive CHECK (estimated_turnaround_days > 0),
    CONSTRAINT chk_grading_recommendation CHECK (
        recommendation IN (
            'STRONG_GRADE',
            'GRADE_ONLY_IF_CONFIDENT_PSA10',
            'HOLD_RAW',
            'DO_NOT_GRADE',
            'INSUFFICIENT_DATA'
        )
    ),
    CONSTRAINT chk_grading_confidence CHECK (confidence_rating IN ('HIGH', 'MEDIUM', 'LOW'))
);

CREATE TABLE grading_scenario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grading_analysis_id BIGINT NOT NULL REFERENCES grading_analysis(id),
    scenario_type VARCHAR(50) NOT NULL,
    assumed_grade VARCHAR(50) NOT NULL,
    expected_graded_value_sgd NUMERIC(19, 2) NOT NULL,
    total_cost_sgd NUMERIC(19, 2) NOT NULL,
    expected_profit_sgd NUMERIC(19, 2) NOT NULL,
    roi_percentage NUMERIC(12, 4) NOT NULL,
    recommendation VARCHAR(80) NOT NULL,
    warning_message VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_grading_scenario_type CHECK (
        scenario_type IN ('CONSERVATIVE', 'BALANCED', 'AGGRESSIVE')
    ),
    CONSTRAINT chk_grading_assumed_grade CHECK (assumed_grade IN ('PSA_8', 'PSA_9', 'PSA_10')),
    CONSTRAINT chk_grading_scenario_values_nonnegative CHECK (
        expected_graded_value_sgd >= 0
        AND total_cost_sgd >= 0
    ),
    CONSTRAINT chk_grading_scenario_recommendation CHECK (
        recommendation IN (
            'STRONG_GRADE',
            'GRADE_ONLY_IF_CONFIDENT_PSA10',
            'HOLD_RAW',
            'DO_NOT_GRADE',
            'INSUFFICIENT_DATA'
        )
    )
);

CREATE INDEX idx_grading_fee_active_company ON grading_fee(active, grading_company, service_level_name);
CREATE INDEX idx_grading_analysis_owner_created ON grading_analysis(app_user_id, created_at DESC);
CREATE INDEX idx_grading_analysis_owned_item ON grading_analysis(owned_item_id);
CREATE INDEX idx_grading_scenario_analysis ON grading_scenario(grading_analysis_id);

INSERT INTO grading_fee (
    grading_company,
    service_level_name,
    fee_sgd,
    estimated_turnaround_days,
    active,
    created_at,
    updated_at
) VALUES (
    'PSA',
    'Manual PSA Standard',
    35.00,
    65,
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);
