CREATE TABLE pokemon_set (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    language_market VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_pokemon_set_name_market UNIQUE (name, language_market),
    CONSTRAINT chk_pokemon_set_language CHECK (language_market IN ('ENGLISH'))
);

CREATE TABLE card (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pokemon_set_id BIGINT NOT NULL REFERENCES pokemon_set(id),
    name VARCHAR(255) NOT NULL,
    card_number VARCHAR(80) NOT NULL,
    language_market VARCHAR(50) NOT NULL,
    variant VARCHAR(80) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_card_language CHECK (language_market IN ('ENGLISH')),
    CONSTRAINT uq_card_identity UNIQUE (pokemon_set_id, name, card_number, language_market, variant)
);

