CREATE TABLE owned_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_user_id BIGINT NOT NULL REFERENCES app_user(id),
    card_id BIGINT NOT NULL REFERENCES card(id),
    item_condition VARCHAR(80) NOT NULL,
    purchase_price_sgd NUMERIC(19, 2) NOT NULL,
    purchase_date DATE NOT NULL,
    graded_status VARCHAR(50) NOT NULL,
    psa_grade INTEGER,
    psa_certification_number VARCHAR(120),
    notes VARCHAR(1000),
    archived_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_purchase_price_nonnegative CHECK (purchase_price_sgd >= 0),
    CONSTRAINT chk_psa_grade_range CHECK (psa_grade IS NULL OR psa_grade BETWEEN 1 AND 10)
);

