CREATE TABLE price_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id BIGINT NOT NULL REFERENCES card(id),
    provider_name VARCHAR(120) NOT NULL,
    source_price NUMERIC(19, 2) NOT NULL,
    source_currency VARCHAR(3) NOT NULL,
    exchange_rate_used NUMERIC(19, 8) NOT NULL,
    market_price_sgd NUMERIC(19, 2) NOT NULL,
    confidence_rating VARCHAR(20) NOT NULL,
    explanation VARCHAR(1000) NOT NULL,
    calculated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_price_snapshot_card_time ON price_snapshot(card_id, calculated_at DESC, id DESC);

