CREATE TABLE portfolio_valuation_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_user_id BIGINT NOT NULL REFERENCES app_user(id),
    total_value_sgd NUMERIC(19, 2) NOT NULL,
    total_cost_basis_sgd NUMERIC(19, 2) NOT NULL,
    unrealized_gain_loss_sgd NUMERIC(19, 2) NOT NULL,
    unrealized_gain_loss_percent NUMERIC(9, 4) NOT NULL,
    item_count INTEGER NOT NULL,
    low_confidence_count INTEGER NOT NULL,
    snapshot_date DATE NOT NULL,
    calculated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    explanation VARCHAR(1000) NOT NULL
);

CREATE INDEX idx_portfolio_snapshot_user_time ON portfolio_valuation_snapshot(app_user_id, calculated_at DESC, id DESC);

