CREATE TABLE exchange_rate_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_currency VARCHAR(3) NOT NULL,
    target_currency VARCHAR(3) NOT NULL,
    exchange_rate NUMERIC(19, 8) NOT NULL,
    rate_source VARCHAR(120) NOT NULL,
    confidence_rating VARCHAR(20) NOT NULL,
    effective_at TIMESTAMP WITH TIME ZONE NOT NULL,
    fetched_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_exchange_rate_snapshot_currency_time
    ON exchange_rate_snapshot(source_currency, target_currency, effective_at DESC, id DESC);
